name: Deploy to EC2

on:
  push:
    branches:
      - main # หรือ branch ที่คุณใช้ deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

    - name: Add EC2 Host to known_hosts
      run: |
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts

    - name: Deploy with Docker Compose
      run: |
        ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "
          mkdir -p ${{ secrets.EC2_TARGET_DIR }}
          cd ${{ secrets.EC2_TARGET_DIR }}

          git init
          git remote add origin https://github.com/tepathipm24/weather-app-react.git
          git pull origin main 
          
          docker-compose down 
          docker-compose up -d --build
        "
